### ISSUE TITLE
Request for Nuget Package

### ISSUE THREAD

**Issue by alhalama** [lordmilko/SwitchvoxAPI#2]
For usage it would be more convenient if there was a Nuget package available.

**Comment by lordmilko** [comment]
Hi @alhalama,

I was thinking about this when you raised your other issue; that issue was the sort of thing that would have been solved if this project had some CI set up. And once you have CI, the next step is to publish to Nuget.

I've been hesitant to put SwitchvoxAPI on Nuget in the past as I'm not sure this project stable enough to warrant that yet; I don't want lots of people using this if I discover I need to radically change something!  I will have a look at this this evening and see if I can do a bit of tidy up to prepare it for Nuget.

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @alhalama,

SwitchvoxAPI is now on NuGet! You can install SwitchvoxAPI by running the following command from the NuGet Package Manager Console

```powershell
Install-Package SwitchvoxAPI
```
SwitchvoxAPI 0.3 simplifies the interfaces of several methods greatly, however does contain a number of breaking changes over SwitchvoxAPI 0.2.

Regards,
lordmilko
